<a href="https://colab.research.google.com/github/newmantic/Cholesky/blob/main/Cholesky.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def cholesky_decomposition(A):
    """
    Perform Cholesky decomposition of a symmetric, positive-definite matrix A.

    Parameters:
    A (np.ndarray): The input matrix of shape (n, n).

    Returns:
    np.ndarray: The lower triangular matrix L such that A = L * L^T.
    """
    n = A.shape[0]
    L = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1):
            sum_l = sum(L[i][k] * L[j][k] for k in range(j))
            if i == j:  # Diagonal elements
                L[i][j] = np.sqrt(A[i][i] - sum_l)
            else:  # Off-diagonal elements
                L[i][j] = (A[i][j] - sum_l) / L[j][j]

    return L

# Testable example:
A = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]])

L = cholesky_decomposition(A)
print("Matrix L:")
print(L)

# Verify that A = L * L^T
A_reconstructed = np.dot(L, L.T)
print("Reconstructed Matrix A:")
print(A_reconstructed)

Matrix L:
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
Reconstructed Matrix A:
[[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]


In [2]:
# example:
A_advanced = np.array([[25, 15, -5],
                       [15, 18,  0],
                       [-5,  0, 11]])

L_advanced = cholesky_decomposition(A_advanced)
print("Advanced Matrix L:")
print(L_advanced)

# Verify that A_advanced = L_advanced * L_advanced^T
A_advanced_reconstructed = np.dot(L_advanced, L_advanced.T)
print("Reconstructed Advanced Matrix A:")
print(A_advanced_reconstructed)

Advanced Matrix L:
[[ 5.  0.  0.]
 [ 3.  3.  0.]
 [-1.  1.  3.]]
Reconstructed Advanced Matrix A:
[[25. 15. -5.]
 [15. 18.  0.]
 [-5.  0. 11.]]
